# Generated by Django 5.2.8 on 2026-03-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_room_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_image',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='Room.room'),
        ),
    ]
