# Generated by Django 5.2.8 on 2026-03-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_alter_room_image_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
    ]
