# Generated by Django 5.2.8 on 2026-03-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
