# Generated by Django 5.2.8 on 2026-03-14 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Room.room'),
            preserve_default=False,
        ),
    ]
