# Generated by Django 5.2.8 on 2026-03-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_usermodel_verify_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_picCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('pinCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='near_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.city_piccode')),
            ],
        ),
    ]
