# Generated by Django 5.2.8 on 2026-03-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0009_city_piccode_near_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='near_by',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Room.city_piccode'),
        ),
    ]
