# Generated by Django 5.2.8 on 2026-03-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0010_alter_near_by_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='near_by',
            name='city',
        ),
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(default='jaipur', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='near_by',
            field=models.CharField(default='Dadi Ka Phatak', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='pin_code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.DeleteModel(
            name='City_picCode',
        ),
        migrations.DeleteModel(
            name='near_by',
        ),
    ]
